### PR TITLE
Add raft leader election

### PR DESCRIPTION
**Pull request by boingram**
Use Hashicorp's [Raft library](https://github.com/hashicorp/raft) to implement Zookeeper-free leader election in Lamport. We can start up a node, which will elect itself as leader. Successive nodes can be started with a -join <addr> flag, which will attempt to join the specified Lamport node. Also included a configuration file and package using [TOML](https://github.com/toml-lang/toml) to reduce the growing amount of command line flags.

### CODE REVIEW

**Comment by RBeaudoin** [comment]
Thanks @boingram , appreciate you stepping up to contribute. Thank you.

Did you have a chacne to run `golint` on the 'server' package? I ran it and there were a few issues. Sorry for not having clear contribution guidelines, but we should run `golint` to make sure the PR passes golang linting

**Comment by boingram** [comment]
Good call, I kinda thought my vim setup was missing something. Just ran golint and updated to reflect changes.

**Comment by RBeaudoin** [comment]
Thanks @boingram I'll take a look here in the next day or so

**Comment by RBeaudoin** [comment]
Hey, thanks again for the changes.

Looks like my latest change to support Homebrew ZK install and tar install resulted in a merge conflict. If you can resolve those I can get this merged into master.

I promise things will be smoother moving forward :)

**Comment by RBeaudoin** [comment]
Nice work at @boingram, thank you

**Pull request merged**
